[features]
resolution = true
skip-lint = false

[programs.localnet]
norr_launch = "4orq3YjidamefZgGufp6uSpdgxdxpNeCfdy6spZas2cE"
norr_claim = "HzV76HzGKqDuhmc2f5VoMDEF3tqo3GYGbMGbYyRYWitg"
norr_fees = "3VNFr1kkLv1mQkpWQSNBJhDJbpLsELPPF7f5YMWHjMy8"
norr_market = "3syw2wKJNu1TCGArkvnZHvJ8xN9mn5oHdr34yrpJdyXB"
norr_boards = "7EtFrHpKzvKYYWYNqimJu8t4UEmDgxTvwyqnGhcuAenB"
norr_social = "4BNL4GDkUFkCdVZTXo9e3KYRDsD32DXdcrTYJXiucs7g"
norr_wrap = "6anK695vF91cd3r2iin9AMRQzWCfJL6sugZywdfj9cdV"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"

[test]
startup_wait = 15000
shutdown_wait = 2000
