[features]
resolution = true
skip-lint = false

[programs.localnet]
norr_launch = "4cpxPRvPm974bLKMJa8TfYyvzuFeQ9sjtFJkz3EhJ4p8"
norr_claim = "4QrYBhxu8crT4Yi33XR6DqQEp1XG52R94rBzgx8QdF9R"
norr_fees = "6qXW6K7UxDmzxotm8XM5uqWiqF6hBokMdkGavbw5Mp6J"
norr_market = "Gx4szwkK1wMYpyZJ6y168ytuPNfC3gq9kehg3XjgMNkV"
norr_boards = "2CfmqDruJHpAqManNjNAfEhCX99NhBAkmCQ73Tt5FXvY"
norr_social = "95naDaDALhhL37JseHMkJFeUqPs8ucNYcaSwZCknScAw"
norr_wrap = "9qLPCBzMENxbTVvFQCACtfD9DnY1KBhz3WFqMzc8u7LU"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"

[test]
startup_wait = 15000
shutdown_wait = 2000
