import { createContext, useContext, useMemo, type ReactNode } from "react";
export type Launch = Readonly<{ id:string; name:string; symbol:string; model:"instant"|"raise"; state:"live"|"setup"|"sealed"|"settled"; creator:string; desk?:string; description:string; price?:string; marketCap?:string; liquidity?:string; target?:string; progress?:number; unlock?:string; splits:readonly Readonly<{name:string;bps:number;role:string}>[] }>;
export type Board = Readonly<{ slug:string; name:string; owner:string; minBps:number; launchCount:number; allowlistOnly:boolean }>;
type Data = Readonly<{ fixture:boolean; cluster:string; genesisHash:string; slot:string|null; commitment:"unavailable"|"processed"|"confirmed"|"finalized"; indexer:"online"|"degraded"|"offline"; launches:readonly Launch[]; boards:readonly Board[] }>;
const fixtures:Data={fixture:true,cluster:"localnet fixture",genesisHash:"fixture-8d71b6a0",slot:"283,904,112",commitment:"finalized",indexer:"degraded",launches:[
 {id:"alpha",name:"Northstar Compute",symbol:"NSTAR",model:"instant",state:"live",creator:"7NKd…x4Qp",desk:"frontier",description:"Open compute coordination with a fixed project supply and public USDC curve.",price:"0.0374",marketCap:"$2.46M",liquidity:"$184.2K",target:"$250K",progress:74,unlock:"16 Mar 2027",splits:[{name:"Creator",bps:7000,role:"creator"},{name:"Frontier desk",bps:1500,role:"partner"},{name:"Treasury",bps:1500,role:"treasury"}]},
 {id:"quiet",name:"Quiet Harbour",symbol:"QHBR",model:"raise",state:"setup",creator:"9yPW…Qm2n",desk:"commons",description:"A sealed-amount raise waiting on the target-cluster confidential-transfer gate.",target:"private while open",splits:[{name:"Creator",bps:7600,role:"creator"},{name:"Commons",bps:1500,role:"partner"},{name:"Rewards",bps:900,role:"treasury"}]},
 {id:"orbit",name:"Orbit Materials",symbol:"ORBT",model:"instant",state:"settled",creator:"4sJH…9wRt",description:"Materials research coordination, graduated into a locked liquidity position.",price:"0.1182",marketCap:"$7.80M",liquidity:"$612.0K",target:"$500K",progress:100,unlock:"permanent",splits:[{name:"Creator",bps:8200,role:"creator"},{name:"Liquidity",bps:1000,role:"partner"},{name:"Treasury",bps:800,role:"treasury"}]}
],boards:[{slug:"frontier",name:"Frontier Desk",owner:"8fTa…19Lp",minBps:1500,launchCount:12,allowlistOnly:true},{slug:"commons",name:"Commons",owner:"F42q…mJ8c",minBps:1000,launchCount:8,allowlistOnly:false}]};
const empty:Data={fixture:false,cluster:"not connected",genesisHash:"unknown",slot:null,commitment:"unavailable",indexer:"offline",launches:[],boards:[]};
const DataContext=createContext<Data>(empty);
export function DataProvider({children}:{children:ReactNode}){const fixture=typeof window!=="undefined"&&(((window as unknown as {__NORR_FIXTURE__?:boolean}).__NORR_FIXTURE__===true)||new URLSearchParams(window.location.search).get("fixture")==="1");const value=useMemo(()=>fixture?fixtures:empty,[fixture]);return <DataContext.Provider value={value}>{children}</DataContext.Provider>}
export const useData=()=>useContext(DataContext);
